name: Pipeline CI/CD - Deploy GitHub Pages

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Baixar código do repositório
      uses: actions/checkout@v4

    - name: Configurar Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Instalar as dependências
      run: npm install

    - name: Rodar os testes (se tiver)
      run: npm test || echo "Sem testes configurados, continuando..."

    - name: Fazer build do projeto
      run: npm run build

    - name: Preparar arquivos para deploy
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - name: Fazer deploy no GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4

    - name: Mandar notificação do resultado
      if: always()
      run: |
        echo "O pipeline terminou com status: ${{ job.status }}"
        echo "URL do deploy: ${{ steps.deployment.outputs.page_url }}"